// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwdgiooebvytnphlfljr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3ZGdpb29lYnZ5dG5waGxmbGpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1OTEwMjgsImV4cCI6MjA3MjE2NzAyOH0.m8SIzr6JsRrULf-4A5HIvrCEVd8gN8geIUM1ZSLzajI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});